// Generated by scripts/generate-font-subset.ts — do not edit.
export const WENKAI_SUBSET_PATHS: string[] = [
  "/fonts/wenkai/wenkai-subset.0.400.woff2",
  "/fonts/wenkai/wenkai-subset.1.400.woff2",
  "/fonts/wenkai/wenkai-subset.2.400.woff2",
  "/fonts/wenkai/wenkai-subset.3.400.woff2",
  "/fonts/wenkai/wenkai-subset.4.400.woff2",
  "/fonts/wenkai/wenkai-subset.5.400.woff2",
  "/fonts/wenkai/wenkai-subset.6.400.woff2",
  "/fonts/wenkai/wenkai-subset.7.400.woff2",
  "/fonts/wenkai/wenkai-subset.8.400.woff2",
  "/fonts/wenkai/wenkai-subset.9.400.woff2",
  "/fonts/wenkai/wenkai-subset.10.400.woff2",
  "/fonts/wenkai/wenkai-subset.11.400.woff2",
  "/fonts/wenkai/wenkai-subset.12.400.woff2"
];
